spring.application.name=dancelab

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://rathnasirisuvinya:DanceLab1234@dancelab.pmhflqs.mongodb.net/dancelab?retryWrites=true&w=majority&appName=DanceLab

# Server settings
server.port=9090

# Set maximum file size for uploaded files
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.web.resources.static-locations=file:uploads/videos/

spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
