spring.application.name=dancelab

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://rathnasirisuvinya:DanceLab1234@dancelab.pmhflqs.mongodb.net/dancelab?retryWrites=true&w=majority&appName=DanceLab

# Server settings
server.port=9090
